/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhatro;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author linhsama
 */
public class TinhTien extends javax.swing.JFrame {

    private int soNguoiDungVS1;
    private int soNguoi;
    /**
     * Creates new form TinhTien
     */
    public TinhTien() {
        initComponents();
        soNguoiDungVS1 = 5;
        soNguoi = 12;
        textSum.setText(String.valueOf(1635689));
        textNuoc.setText(String.valueOf(360000));
        lblTongNguoi.setText("Có tất cả 12 người");
        lblNguoiVs1.setText("có 5 người dùng vs tầng 1");
        
        table.setValueAt(743, 0, 1);
        table.setValueAt(780, 0, 2);

        table.setValueAt(286, 1, 1);
        table.setValueAt(377, 1, 2);
        table.setValueAt(true, 1, 3);
        table.setValueAt(1, 1, 4);
        
        table.setValueAt(285, 2, 1);
        table.setValueAt(357, 2, 2);
        table.setValueAt(true, 2, 3);
        table.setValueAt(1, 2, 4);
        
        table.setValueAt(20831, 3, 1);
        table.setValueAt(21031, 3, 2);
        table.setValueAt(false, 3, 3);
        table.setValueAt(4, 3, 4);
        
        table.setValueAt(663, 4, 1);
        table.setValueAt(766, 4, 2);
        table.setValueAt(true, 4, 3);
        table.setValueAt(2, 4, 4);
        
        table.setValueAt(11237, 5, 1);
        table.setValueAt(11592, 5, 2);
        table.setValueAt(false, 5, 3);
        table.setValueAt(3, 5, 4);
        
        table.setValueAt(730, 6, 1);
        table.setValueAt(934, 6, 2);
        table.setValueAt(true, 6, 3);
        table.setValueAt(1, 6, 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textSum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNuoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblTongtienDien = new javax.swing.JLabel();
        lblNguoiVs1 = new javax.swing.JLabel();
        lblTongNguoi = new javax.swing.JLabel();
        lblchenhLech = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Vs tầng 1", null, null,  new Boolean(false), null, null},
                {"101", null, null, null, null, null},
                {"201", null, null, null, null, null},
                {"202", null, null, null, null, null},
                {"301", null, null, null, null, null},
                {"302", null, null, null, null, null},
                {"401", null, null, null, null, null}
            },
            new String [] {
                "Phòng", "điện tháng trước", "điện tháng này", "Phòng vs tầng 1", "Số người", "Số tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(20);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(60);
            table.getColumnModel().getColumn(0).setPreferredWidth(60);
            table.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButton1.setText("Tính tiền");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hóa đơn điện");

        jLabel2.setText("vnd");

        jLabel3.setText("Nước");

        jLabel4.setText("vnd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textSum, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(textNuoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblchenhLech, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTongtienDien, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(lblTongNguoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNguoiVs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(textSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(lblTongtienDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblchenhLech, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(textNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(lblTongNguoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNguoiVs1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sum = textSum.getText();
        if (sum.isEmpty()) {
            lblTongtienDien.setText("sum empty");
            return;
        }
        String nuoc = textNuoc.getText();
        float tienNuoc = 0;
        if (nuoc.isEmpty()) {
            lblTongtienDien.setText("nuoc empty");
        } else
            tienNuoc = Integer.parseInt(nuoc)/soNguoi;
        float sumMoney = Float.parseFloat(sum);
        System.out.println("sumMoney: " + sumMoney);
        float tienVS1 = 0;
        List<Room> rooms = new ArrayList();
        for (int i = 0; i < 7; i ++) {
            int thangNay = 0;
            int thangTruoc = 0;
            float vs = 0;
            int nguoi = 0;
            for (int j = 1; j < 5; j++) {
                Object cell = table.getValueAt(i, j);
                if (cell == null) {
                    lblTongtienDien.setText("chua nhap o " + i + "," + j);
                    if (j==3) {
                        cell = false;
                    }
                }
                if (j == 1) {
                    thangTruoc = Integer.parseInt(cell.toString());
                } else if (j == 2) {
                    thangNay = Integer.parseInt(cell.toString());
                } else {
                    if (i == 0) {
                        break;
                    }
                    if (j == 3 && Boolean.valueOf(cell.toString()) == true) {
                        vs = tienVS1/soNguoiDungVS1;
                    } else if (j == 4) {
                        nguoi = Integer.parseInt(cell.toString());
                    }
                }
            }
            Room room = new Room(i, thangTruoc, thangNay, vs, tienNuoc, nguoi);
            if (i == 0) {
                tienVS1 = room.getResult();
            } else {
                rooms.add(room);            
            }
        }
        float tongSoDienCacPhong = 0;
        for (Room r: rooms) {
            tongSoDienCacPhong += r.getResult();
        }
        float soDienChungChiaDauNguoi = (sumMoney-tongSoDienCacPhong)/soNguoi;
        System.out.println("so tien cac phong:" + tongSoDienCacPhong);
        System.out.println(soDienChungChiaDauNguoi*soNguoi);
        for (Room r: rooms) {
            r.soTienPhaiTra(soDienChungChiaDauNguoi);
            table.setValueAt(r.tienMoiPhong(), r.getRow(), 5);
        }
        for (Room r: rooms) {
            sumMoney -= r.tienMoiPhong();
        }
        lblTongtienDien.setText("tổng tiền điện các phòng: " + tongSoDienCacPhong);
        lblchenhLech.setText("(hóa đơn) - (tổng tiền điện các phòng): " + soDienChungChiaDauNguoi*soNguoi);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNguoiVs1;
    private javax.swing.JLabel lblTongNguoi;
    private javax.swing.JLabel lblTongtienDien;
    private javax.swing.JLabel lblchenhLech;
    private javax.swing.JTable table;
    private javax.swing.JTextField textNuoc;
    private javax.swing.JTextField textSum;
    // End of variables declaration//GEN-END:variables
}
